version: v1
name: product-category-profiling
type: workflow
tags:
description: The job is to profiling product_category data 
workflow:
  dag:
    - name: profiling-pcategory
      description: The job performs profiling on product_category data
      spec:
        stack: flare:3.0
        compute: runnable-default
        persistentVolume:
          name: persistent-v
          directory: fides
        flare:
          job:
            explain: true
            inputs:
              - name: profile_product_category
                dataset: dataos://icebase:sports/sample_product_category?acl=rw
                format: Iceberg

            logLevel: WARN
            profile:
              level: basic
              