version: v1
name: psub-category-profiling
type: workflow
tags:
description: The job is to profiling psub_category data 
workflow:
  dag:
    - name: profiling-psub-category
      description: The job performs profiling on psub_category data
      spec:
        stack: flare:3.0
        compute: runnable-default
        persistentVolume:
          name: persistent-v
          directory: fides
        flare:
          job:
            explain: true
            inputs:
              - name: profile_psub_category
                dataset: dataos://icebase:sports/sample_product_sub_category?acl=rw
                format: Iceberg

            logLevel: WARN
            profile:
              level: basic
              