version: v1
name: product-profiling
type: workflow
tags:
description: The job is to profiling product data 
workflow:
  dag:
    - name: profiling-product
      description: The job performs profiling on product data
      spec:
        stack: flare:3.0
        compute: runnable-default
        persistentVolume:
          name: persistent-v
          directory: fides 
        flare:
          job:
            explain: true
            inputs:
              - name: profile_product
                dataset: dataos://icebase:sports/sample_product?acl=rw
                format: Iceberg

            logLevel: WARN
            profile:
              level: basic
              